apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
spec:
  containers:
  - name: nginx 
    image: nginx
    env:
      - name: course
        valueFrom:
          configMapKeyRef:
            name: nginx-config
            key: course
      - name: trainer
        valueFrom:
          configMapKeyRef:
            name: nginx-config
            key: trainer
      - name: duration
        valueFrom:
          configMapKeyRef:
            name: nginx-config
            key: duration