apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    project: expense
    module: bckend
    environment: dev
  ports:
  - name: nginx-svc-port
    protocol: TCP
    port: 80
    targetPort: 80
  