apiVersion: v1
kind: Namespace
metadata:
  name: testing
  labels:
    project: testing
    environment: test
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx
  namespace: testing
  labels:
    project: testing
    environment: test
  annotations:
    imageregistry: "https://hub.docker.com/"
    buildURL: "https://jenkins.joindevops.com"
  
spec:
  containers:
  - name: nginx
    image: nginx
    env: 
      - name: course
        value: devops
      - name: trainer
        value: "siva"
      - name: duration
        value: "120Hrs"
    requests: # minimum limits
      cpu: 100m 
      memory: 64Mi
    limits: # maximum limits
      cpu: 120m
      memory: 128Mi